// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzATgT5NNhigt5TutL2hI1dL4lp2QHRc',
    appId: '1:1062697430678:web:261ee82429df2e1aa95cb7',
    messagingSenderId: '1062697430678',
    projectId: 'fridge-to-fork-a17de',
    authDomain: 'fridge-to-fork-a17de.firebaseapp.com',
    storageBucket: 'fridge-to-fork-a17de.firebasestorage.app',
    measurementId: 'G-RG88L92YN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7KXQYIuHR6QF6-iKRDByQOKWzMDo-II8',
    appId: '1:1062697430678:android:6433aa4dd6c16fd2a95cb7',
    messagingSenderId: '1062697430678',
    projectId: 'fridge-to-fork-a17de',
    storageBucket: 'fridge-to-fork-a17de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpOWppMEXmXC-He0kQH2UT-n92ErAuh4',
    appId: '1:1062697430678:ios:84749f8cc092acb1a95cb7',
    messagingSenderId: '1062697430678',
    projectId: 'fridge-to-fork-a17de',
    storageBucket: 'fridge-to-fork-a17de.firebasestorage.app',
    iosBundleId: 'com.example.fridgeToForkAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpOWppMEXmXC-He0kQH2UT-n92ErAuh4',
    appId: '1:1062697430678:ios:84749f8cc092acb1a95cb7',
    messagingSenderId: '1062697430678',
    projectId: 'fridge-to-fork-a17de',
    storageBucket: 'fridge-to-fork-a17de.firebasestorage.app',
    iosBundleId: 'com.example.fridgeToForkAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzATgT5NNhigt5TutL2hI1dL4lp2QHRc',
    appId: '1:1062697430678:web:99aabbf8521e316fa95cb7',
    messagingSenderId: '1062697430678',
    projectId: 'fridge-to-fork-a17de',
    authDomain: 'fridge-to-fork-a17de.firebaseapp.com',
    storageBucket: 'fridge-to-fork-a17de.firebasestorage.app',
    measurementId: 'G-ZS36W7WQ1H',
  );
}
